#### First the understatapi

-- This package is not actively maintained so use at your own risk

In [1]:
!pip install understatapi --quiet

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
selenium 4.41.0 requires certifi>=2026.1.4, but you have certifi 2025.11.12 which is incompatible.
selenium 4.41.0 requires urllib3[socks]<3.0,>=2.6.3, but you have urllib3 1.26.5 which is incompatible.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [2]:
import pandas as pd
import understatapi

client = understatapi.UnderstatClient()

In [3]:
# Let's first get data from a league to retrieve a list of matches
league_data = client.league(league="EPL").get_match_data(season="2024")
league_data[0]

{'id': '26602',
 'isResult': True,
 'h': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
 'a': {'id': '228', 'title': 'Fulham', 'short_title': 'FLH'},
 'goals': {'h': '1', 'a': '0'},
 'xG': {'h': '2.04268', 'a': '0.418711'},
 'datetime': '2024-08-16 19:00:00',
 'forecast': {'w': '0.8069', 'd': '0.1489', 'l': '0.0442'}}

In [4]:
# now we can use the match id to get the match data
shot_data = client.match(match=league_data[0]["id"]).get_shot_data()
shot_data['h'][0]

{'id': '584630',
 'minute': '19',
 'result': 'MissedShots',
 'X': '0.970999984741211',
 'Y': '0.6730000305175782',
 'xG': '0.050078392028808594',
 'player': 'Bruno Fernandes',
 'h_a': 'h',
 'player_id': '1228',
 'situation': 'OpenPlay',
 'season': '2024',
 'shotType': 'LeftFoot',
 'match_id': '26602',
 'h_team': 'Manchester United',
 'a_team': 'Fulham',
 'h_goals': '1',
 'a_goals': '0',
 'date': '2024-08-16 19:00:00',
 'player_assisted': 'Lisandro Martínez',
 'lastAction': 'Chipped'}

In [5]:
# now let's get all of the data for a player, with this method you need to use the player_id
# This is literally every shot they ever took. 

player_data = client.player(player='1228').get_shot_data()
player_data[0]

{'id': '41640',
 'minute': '79',
 'result': 'BlockedShot',
 'X': '0.730999984741211',
 'Y': '0.5059999847412109',
 'xG': '0.031210700049996376',
 'player': 'Bruno Fernandes',
 'h_a': 'h',
 'player_id': '1228',
 'situation': 'OpenPlay',
 'season': '2014',
 'shotType': 'RightFoot',
 'match_id': '5158',
 'h_team': 'Udinese',
 'a_team': 'Empoli',
 'h_goals': '2',
 'a_goals': '0',
 'date': '2014-08-31 19:45:00',
 'player_assisted': 'Cyril Théréau',
 'lastAction': 'Pass'}

In [6]:
df = pd.DataFrame(player_data)

In [7]:
df

,id,minute,result,X,Y,xG,player,h_a,player_id,situation,season,shotType,match_id,h_team,a_team,h_goals,a_goals,date,player_assisted,lastAction
0,41640,79,BlockedShot,0.730999984741211,0.5059999847412109,0.031210700049996376,Bruno Fernandes,h,1228,OpenPlay,2014,RightFoot,5158,Udinese,Empoli,2,0,2014-08-31 19:45:00,Cyril Théréau,Pass
1,41641,82,MissedShots,0.9569999694824218,0.6170000076293946,0.11918000131845474,Bruno Fernandes,h,1228,OpenPlay,2014,RightFoot,5158,Udinese,Empoli,2,0,2014-08-31 19:45:00,Antonio Di Natale,Chipped
2,41643,86,SavedShot,0.77,0.5170000076293946,0.037953298538923264,Bruno Fernandes,h,1228,OpenPlay,2014,RightFoot,5158,Udinese,Empoli,2,0,2014-08-31 19:45:00,Panagiotis Kone,Pass
3,41807,47,BlockedShot,0.759000015258789,0.664000015258789,0.01848829910159111,Bruno Fernandes,a,1228,OpenPlay,2014,RightFoot,5110,Juventus,Udinese,2,0,2014-09-13 19:45:00,Antonio Di Natale,LayOff
4,42170,42,BlockedShot,0.754000015258789,0.534000015258789,0.02486089989542961,Bruno Fernandes,h,1228,OpenPlay,2014,LeftFoot,5125,Udinese,Napoli,1,0,2014-09-21 17:00:00,Emmanuel Badu,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,671574,63,MissedShots,0.78,0.6969999694824218,0.016284747049212456,Bruno Fernandes,h,1228,OpenPlay,2025,RightFoot,29055,Manchester United,Crystal Palace,2,1,2026-03-01 14:00:00,Casemiro,Chipped
756,672324,81,MissedShots,0.81,0.5929999923706055,0.04061715304851532,Bruno Fernandes,a,1228,OpenPlay,2025,RightFoot,29065,Newcastle United,Manchester United,2,1,2026-03-04 20:15:00,Matheus Cunha,Pass
757,674425,19,BlockedShot,0.7269999694824218,0.3820000076293945,0.013531903736293316,Bruno Fernandes,h,1228,OpenPlay,2025,LeftFoot,29074,Manchester United,Aston Villa,3,1,2026-03-15 14:00:00,Amad Diallo Traore,Pass
758,674431,42,MissedShots,0.7390000152587891,0.6880000305175781,0.03037339262664318,Bruno Fernandes,h,1228,OpenPlay,2025,RightFoot,29074,Manchester United,Aston Villa,3,1,2026-03-15 14:00:00,Kobbie Mainoo,Pass
759,674433,50,BlockedShot,0.8030000305175782,0.31,0.021025920286774635,Bruno Fernandes,h,1228,OpenPlay,2025,RightFoot,29074,Manchester United,Aston Villa,3,1,2026-03-15 14:00:00,Amad Diallo Traore,Pass

In [8]:
df.to_csv('/Users/mckayjohns/Documents/GitHub/youtube-videos/data/bruno_fernandes_all_shots.csv', index=False)

OSError: Cannot save file into a non-existent directory: '/Users/mckayjohns/Documents/GitHub/youtube-videos/data'

#### Now let's scrape it ourselves with requests and BeautifulSoup. This is a bit more work so we'll look at only a single match
You'll need to install:
- requests
- BeautifulSoup
- lxml

In [ ]:
import re
import requests
import json

from bs4 import BeautifulSoup

response = requests.get("https://understat.com/match/27760")
print(response.status_code)

200

In [ ]:
soup = BeautifulSoup(response.content, 'html.parser')
ugly_soup = str(soup)

In [ ]:
# strip unnecessary symbols and get only JSON data
shots_data = re.search("var shotsData .*= JSON.parse\('(.*)'\)", ugly_soup).group(1)
data = json.loads(shots_data.encode('utf8').decode('unicode_escape'))

In [ ]:
data

{'h': [{'id': '590347',
   'minute': '2',
   'result': 'SavedShot',
   'X': '0.8930000305175781',
   'Y': '0.36200000762939455',
   'xG': '0.011930749751627445',
   'player': 'Ramy Bensebaini',
   'h_a': 'h',
   'player_id': '3349',
   'situation': 'SetPiece',
   'season': '2024',
   'shotType': 'Head',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': None,
   'lastAction': 'Aerial'},
  {'id': '590348',
   'minute': '5',
   'result': 'MissedShots',
   'X': '0.7959999847412109',
   'Y': '0.40099998474121096',
   'xG': '0.040396686643362045',
   'player': 'Pascal Groß',
   'h_a': 'h',
   'player_id': '239',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Julian Ryerson',
   'lastAction': 'BallTouch'},
  {'id': '590349',
   'minute': '10',
   'result': 'Goal',
   'X': '0.8230000305175781',
   'Y': '0.51',
   'xG': '0.07171561568975449',
   'player': 'Donyell Malen',
   'h_a': 'h',
   'player_id': '9749',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Karim Adeyemi',
   'lastAction': 'Pass'},
  {'id': '590350',
   'minute': '16',
   'result': 'Goal',
   'X': '0.915',
   'Y': '0.65',
   'xG': '0.34929072856903076',
   'player': 'Karim Adeyemi',
   'h_a': 'h',
   'player_id': '10772',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Julian Brandt',
   'lastAction': 'Pass'},
  {'id': '590355',
   'minute': '36',
   'result': 'BlockedShot',
   'X': '0.8590000152587891',
   'Y': '0.7030000305175781',
   'xG': '0.08351726084947586',
   'player': 'Serhou Guirassy',
   'h_a': 'h',
   'player_id': '3738',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Felix Nmecha',
   'lastAction': 'Chipped'},
  {'id': '590357',
   'minute': '40',
   'result': 'Goal',
   'X': '0.8619999694824219',
   'Y': '0.5159999847412109',
   'xG': '0.11208920180797577',
   'player': 'Karim Adeyemi',
   'h_a': 'h',
   'player_id': '10772',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Julian Ryerson',
   'lastAction': 'Pass'},
  {'id': '590358',
   'minute': '44',
   'result': 'BlockedShot',
   'X': '0.845',
   'Y': '0.27100000381469724',
   'xG': '0.02453427016735077',
   'player': 'Donyell Malen',
   'h_a': 'h',
   'player_id': '9749',
   'situation': 'SetPiece',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Julian Brandt',
   'lastAction': 'Pass'},
  {'id': '590360',
   'minute': '48',
   'result': 'BlockedShot',
   'X': '0.894000015258789',
   'Y': '0.4470000076293945',
   'xG': '0.05760763958096504',
   'player': 'Serhou Guirassy',
   'h_a': 'h',
   'player_id': '3738',
   'situation': 'FromCorner',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Pascal Groß',
   'lastAction': 'Cross'},
  {'id': '590361',
   'minute': '51',
   'result': 'MissedShots',
   'X': '0.845',
   'Y': '0.47900001525878905',
   'xG': '0.11947015672922134',
   'player': 'Donyell Malen',
   'h_a': 'h',
   'player_id': '9749',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Karim Adeyemi',
   'lastAction': 'Pass'},
  {'id': '590363',
   'minute': '58',
   'result': 'MissedShots',
   'X': '0.909000015258789',
   'Y': '0.4909999847412109',
   'xG': '0.5432764291763306',
   'player': 'Serhou Guirassy',
   'h_a': 'h',
   'player_id': '3738',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'LeftFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Karim Adeyemi',
   'lastAction': 'Pass'},
  {'id': '590366',
   'minute': '66',
   'result': 'SavedShot',
   'X': '0.9219999694824219',
   'Y': '0.525',
   'xG': '0.5830580592155457',
   'player': 'Serhou Guirassy',
   'h_a': 'h',
   'player_id': '3738',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '590369',
   'minute': '89',
   'result': 'BlockedShot',
   'X': '0.8440000152587891',
   'Y': '0.5479999923706055',
   'xG': '0.08599820733070374',
   'player': 'Maximilian Beier',
   'h_a': 'h',
   'player_id': '8137',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'LeftFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '590370',
   'minute': '92',
   'result': 'Goal',
   'X': '0.885',
   'Y': '0.5',
   'xG': '0.75777667760849',
   'player': 'Emre Can',
   'h_a': 'h',
   'player_id': '604',
   'situation': 'Penalty',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': None,
   'lastAction': 'Standard'}],
 'a': [{'id': '590351',
   'minute': '18',
   'result': 'SavedShot',
   'X': '0.7440000152587891',
   'Y': '0.49900001525878906',
   'xG': '0.019263489171862602',
   'player': 'Léo Scienza',
   'h_a': 'a',
   'player_id': '12986',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': None,
   'lastAction': 'Dispossessed'},
  {'id': '590352',
   'minute': '20',
   'result': 'BlockedShot',
   'X': '0.825',
   'Y': '0.7090000152587891',
   'xG': '0.09373574703931808',
   'player': 'Léo Scienza',
   'h_a': 'a',
   'player_id': '12986',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Marvin Pieringer',
   'lastAction': 'LayOff'},
  {'id': '590353',
   'minute': '23',
   'result': 'BlockedShot',
   'X': '0.775',
   'Y': '0.51',
   'xG': '0.015238136053085327',
   'player': 'Jonas Föhrenbach',
   'h_a': 'a',
   'player_id': '5347',
   'situation': 'FromCorner',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Lennard Maloney',
   'lastAction': 'HeadPass'},
  {'id': '590354',
   'minute': '35',
   'result': 'SavedShot',
   'X': '0.9109999847412109',
   'Y': '0.500999984741211',
   'xG': '0.2738282382488251',
   'player': 'Marvin Pieringer',
   'h_a': 'a',
   'player_id': '11856',
   'situation': 'SetPiece',
   'season': '2024',
   'shotType': 'Head',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Léo Scienza',
   'lastAction': 'Cross'},
  {'id': '590356',
   'minute': '38',
   'result': 'Goal',
   'X': '0.9259999847412109',
   'Y': '0.49700000762939456',
   'xG': '0.14551830291748047',
   'player': 'Marvin Pieringer',
   'h_a': 'a',
   'player_id': '11856',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'Head',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Omar Traoré',
   'lastAction': 'Cross'},
  {'id': '590359',
   'minute': '46',
   'result': 'MissedShots',
   'X': '0.9119999694824219',
   'Y': '0.705',
   'xG': '0.05068356171250343',
   'player': 'Paul Wanner',
   'h_a': 'a',
   'player_id': '10245',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'LeftFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Jan Schöppner',
   'lastAction': 'Pass'},
  {'id': '590362',
   'minute': '57',
   'result': 'BlockedShot',
   'X': '0.8619999694824219',
   'Y': '0.6880000305175781',
   'xG': '0.048226162791252136',
   'player': 'Léo Scienza',
   'h_a': 'a',
   'player_id': '12986',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Paul Wanner',
   'lastAction': 'Pass'},
  {'id': '590364',
   'minute': '62',
   'result': 'BlockedShot',
   'X': '0.8430000305175781',
   'Y': '0.565',
   'xG': '0.06455931812524796',
   'player': 'Léo Scienza',
   'h_a': 'a',
   'player_id': '12986',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'RightFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Marvin Pieringer',
   'lastAction': 'BallTouch'},
  {'id': '590365',
   'minute': '63',
   'result': 'BlockedShot',
   'X': '0.875999984741211',
   'Y': '0.5540000152587891',
   'xG': '0.07842864096164703',
   'player': 'Léo Scienza',
   'h_a': 'a',
   'player_id': '12986',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'LeftFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': None,
   'lastAction': 'Rebound'},
  {'id': '590367',
   'minute': '73',
   'result': 'Goal',
   'X': '0.885',
   'Y': '0.5',
   'xG': '0.75777667760849',
   'player': 'Maximilian Breunig',
   'h_a': 'a',
   'player_id': '11849',
   'situation': 'Penalty',
   'season': '2024',
   'shotType': 'LeftFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': None,
   'lastAction': 'Standard'},
  {'id': '590368',
   'minute': '85',
   'result': 'MissedShots',
   'X': '0.9230000305175782',
   'Y': '0.654000015258789',
   'xG': '0.07186885178089142',
   'player': 'Jonas Föhrenbach',
   'h_a': 'a',
   'player_id': '5347',
   'situation': 'OpenPlay',
   'season': '2024',
   'shotType': 'LeftFoot',
   'match_id': '27760',
   'h_team': 'Borussia Dortmund',
   'a_team': 'FC Heidenheim',
   'h_goals': '4',
   'a_goals': '2',
   'date': '2024-09-13 18:30:00',
   'player_assisted': 'Mikkel Kaufmann',
   'lastAction': 'Pass'}]}

In [ ]:
h_df = pd.DataFrame(data['h'])

In [ ]:
h_df

,id,minute,result,X,Y,xG,player,h_a,player_id,situation,season,shotType,match_id,h_team,a_team,h_goals,a_goals,date,player_assisted,lastAction
0,590347,2,SavedShot,0.8930000305175781,0.36200000762939455,0.011930749751627445,Ramy Bensebaini,h,3349,SetPiece,2024,Head,27760,Borussia Dortmund,FC Heidenheim,4,2,2024-09-13 18:30:00,None,Aerial
1,590348,5,MissedShots,0.7959999847412109,0.40099998474121096,0.040396686643362045,Pascal Groß,h,239,OpenPlay,2024,RightFoot,27760,Borussia Dortmund,FC Heidenheim,4,2,2024-09-13 18:30:00,Julian Ryerson,BallTouch
2,590349,10,Goal,0.8230000305175781,0.51,0.07171561568975449,Donyell Malen,h,9749,OpenPlay,2024,RightFoot,27760,Borussia Dortmund,FC Heidenheim,4,2,2024-09-13 18:30:00,Karim Adeyemi,Pass
3,590350,16,Goal,0.915,0.65,0.34929072856903076,Karim Adeyemi,h,10772,OpenPlay,2024,RightFoot,27760,Borussia Dortmund,FC Heidenheim,4,2,2024-09-13 18:30:00,Julian Brandt,Pass
4,590355,36,BlockedShot,0.8590000152587891,0.7030000305175781,0.08351726084947586,Serhou Guirassy,h,3738,OpenPlay,2024,RightFoot,27760,Borussia Dortmund,FC Heidenheim,4,2,2024-09-13 18:30:00,Felix Nmecha,Chipped
5,590357,40,Goal,0.8619999694824219,0.5159999847412109,0.11208920180797577,Karim Adeyemi,h,10772,OpenPlay,2024,RightFoot,27760,Borussia Dortmund,FC Heidenheim,4,2,2024-09-13 18:30:00,Julian Ryerson,Pass
6,590358,44,BlockedShot,0.845,0.27100000381469724,0.02453427016735077,Donyell Malen,h,9749,SetPiece,2024,RightFoot,27760,Borussia Dortmund,FC Heidenheim,4,2,2024-09-13 18:30:00,Julian Brandt,Pass
7,590360,48,BlockedShot,0.894000015258789,0.4470000076293945,0.05760763958096504,Serhou Guirassy,h,3738,FromCorner,2024,RightFoot,27760,Borussia Dortmund,FC Heidenheim,4,2,2024-09-13 18:30:00,Pascal Groß,Cross
8,590361,51,MissedShots,0.845,0.47900001525878905,0.11947015672922134,Donyell Malen,h,9749,OpenPlay,2024,RightFoot,27760,Borussia Dortmund,FC Heidenheim,4,2,2024-09-13 18:30:00,Karim Adeyemi,Pass
9,590363,58,MissedShots,0.909000015258789,0.4909999847412109,0.5432764291763306,Serhou Guirassy,h,3738,OpenPlay,2024,LeftFoot,27760,Borussia Dortmund,FC Heidenheim,4,2,2024-09-13 18:30:00,Karim Adeyemi,Pass
10,590366,66,SavedShot,0.9219999694824219,0.525,0.5830580592155457,Serhou Guirassy,h,3738,OpenPlay,2024,RightFoot,27760,Borussia Dortmund,FC Heidenheim,4,2,2024-09-13 18:30:00,None,None
11,590369,89,BlockedShot,0.8440000152587891,0.5479999923706055,0.08599820733070374,Maximilian Beier,h,8137,OpenPlay,2024,LeftFoot,27760,Borussia Dortmund,FC Heidenheim,4,2,2024-09-13 18:30:00,None,None
12,590370,92,Goal,0.885,0.5,0.75777667760849,Emre Can,h,604,Penalty,2024,RightFoot,27760,Borussia Dortmund,FC Heidenheim,4,2,2024-09-13 18:30:00,None,Standard